# jitpack.yml
jdk:
  - openjdk17
gradle:
  version: 8.2.1
  args: --stacktrace --info
before_install:
  - chmod +x gradlew   # 确保 gradlew 有执行权限
  - ./gradlew clean    # 预清理
install:
  - ./gradlew clean assembleRelease  # 根据需要调整任务名